name: GitHub Snake

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # roda todo dia Ã  meia-noite

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate contribution snake
        uses: platane/snk@v2.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: github-contribution-grid-snake.svg
          color: '#16a34a'
          background: 'transparent'
      - name: Commit SVG
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Update snake" || echo "No changes to commit"
          git push
